export const ADMIN_SIGNIN_REQUEST = 'ADMIN_SIGNIN_REQUEST'
export const ADMIN_SIGNIN_SUCCESS = 'ADMIN_SIGNIN_SUCCESS'
export const ADMIN_SIGNIN_FAIL = 'ADMIN_SIGNIN_FAIL'
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT'

export const ADMIN_USERS_FETCH_REQUEST = 'ADMIN_USERS_FETCH_REQUEST'
export const ADMIN_USERS_FETCH_SUCCESS = 'ADMIN_USERS_FETCH_SUCCESS'
export const ADMIN_USERS_FETCH_FAIL = 'ADMIN_USERS_FETCH_FAIL'
export const ADMIN_USERS_FETCH_RESET = 'ADMIN_USERS_FETCH_RESET'

export const ADMIN_USERS_DELETE_REQUEST = 'ADMIN_USERS_DELETE_REQUEST'
export const ADMIN_USERS_DELETE_SUCCESS = 'ADMIN_USERS_DELETE_SUCCESS'
export const ADMIN_USERS_DELETE_FAIL = 'ADMIN_USERS_DELETE_FAIL'


export const ADMIN_ADD_USER_REQUEST = 'ADMIN_ADD_USER_REQUEST'
export const ADMIN_ADD_USER_SUCCESS = 'ADMIN_ADD_USER_SUCCESS'
export const ADMIN_ADD_USER_FAIL = 'ADMIN_ADD_USER_FAIL'
export const ADMIN_ADD_USER_RESET = 'ADMIN_ADD_USER_RESET'

export const ADMIN_EDIT_USER_REQUEST = 'ADMIN_EDIT_USER_REQUEST'
export const ADMIN_EDIT_USER_SUCCESS = 'ADMIN_EDIT_USER_SUCCESS'
export const ADMIN_EDIT_USER_FAIL = 'ADMIN_EDIT_USER_FAIL'
export const ADMIN_EDIT_USER_RESET = 'ADMIN_EDIT_USER_RESET'

export const USER_COUNT_INCREMENT = 'USER_COUNT_INCREMENT'
export const USER_COUNT_DECREMENT = 'USER_COUNT_DECREMENT'
export const USER_COUNT = 'USER_COUNT'

