export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL'
export const USER_SIGNIN_RESET = 'USER_SIGNIN_RESET'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'
export const USER_SIGNUP_RESET = 'USER_SIGNUP_RESET'

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'
export const USER_PROFILE_RESET = 'USER_PROFILE_RESET'

export const USER_PROFILE_EDIT_REQUEST = 'USER_PROFILE_EDIT_REQUEST'
export const USER_PROFILE_EDIT_SUCCESS = 'USER_PROFILE_EDIT_SUCCESS'
export const USER_PROFILE_EDIT_FAIL = 'USER_PROFILE_EDIT_FAIL'
export const USER_PROFILE_EDIT_RESET = 'USER_PROFILE_EDIT_RESET'






